### ISSUE TITLE
List Header Issue: making it a bit more flexible

### ISSUE THREAD

**Issue by adrianmg** [primer/figma#2]
Some feedback:
- Having some items locked by default slows me down when trying to customize the component
- I wonder if we could make the different elements a bit more flexible, so whenever I hide one, the rest redistribute accordingly so I'm not forced to detach them to make them work as I'd love to

Video: https://cln.sh/fhvQsB9jofokmCMHpzjT

**Comment by ashygee** [comment]
Thanks @adrianmg! I'm adding this to the Figma backlog. From first glance it looks like we can restructure this component to use autolayout and also variants.

Is there anything specific you'd expect in terms of flexibility other than the redistribution?

**Comment by ashygee** [comment]
@adrianmg this has been fixed in this [release](https://github.com/primer/figma/releases/tag/2021.01.20). I'll continue to iterate and update this component with variant options but the auto layout has been corrected in this current version. 


https://user-images.githubusercontent.com/10384315/105562620-c18a8b00-5ccf-11eb-85fa-27e55a6b4ed2.mp4
